data=[['HI1','No bootable device found.','1. Switch off the system. \n2. Disconnect all power cables to the servers power supply units.\n3. Remove the system cover.\n4. Reseat all the cables of hard drive backplane at both ends.\n5. Reseat all the drives.\n6. Replace the system cover.\n7. Connect the power cables to the servers power supply units.\n8. Power on the system.\n9. To enter UEFI, Press F2.\n10. Verify that all installed drives are detected in controller BIOS, if not detected refer to the Troubleshooting Hard drive issues section.\n11. Ensure that in BIOS the RAID setting is set to RAID mode for SATA drives.\n12. Save the setting, and reboot the server.\n13. If the issue persists, contact Dell Technical Support for assistance.'],
      ['HI2','USB device not connected','1. Disconnect the device and reconnect them.\n2. If the problem persists, connect the keyboard and/or mouse to another USB port on the system.\n3. Turn off all attached USB devices, and disconnect them from the system and restart the system.\n5. Reconnect and turn on each USB device one at a time.\n6.If the problem persists, get help from the support center.'],
      ['HI3','Battery status not available','1.Check Battery Connections.\n2. Update battery drivers.\n3. Perform power reset.\n4. Check for a newer version of Windows.'],
      ['HI4','High CPU usage','1. Close unnecessary programs.\n2.Restart the PC.\n3. Update the software.\n4. Malware scan.'],
      ['HI5','High RAM usage','1. Restart your computer.\n2. Browser extensions.\n3. Adjust virtual memory.\n4. Optimize Software Settings.\n5. Add more RAM.'],
      ['HI6','High disk usage','1.Close Unnecessary Programs.\n2.Restart Your Computer.\n3.Check for Windows Updates.\n4.Clear Temporary Files.\n5.Upgrade Your Storage Drive.\n6.Check for Disk Fragmentation.\n7.Consider Using a Disk Cleanup Tool'],
      ['HI7','Camera is not working.','1. Check Camera Privacy Settings.\n2. Check camera hardware.\n3. Update camera drivers and restart your computer.\n4. Reset camera application.'],
      ['HI8','Microphone not working.','1. Check microphone privacy settings.\n2. Update mirophone drivers and restart your computer.\n3. Check recording devices.'],
      ['SI1','Wi-Fi Connection Error','1.Make sure your Wi-Fi router is powered on and functioning. Look for indicator lights on the router and ensure your devices Wi-Fi is turned on.\n2.Restart Your Computer or Device.\n3. On your device, forget the Wi-Fi network, then reconnect to it. This clears any potential connection issues. \n4. Reset Network Settings. \n5. Reboot the router. \n6. Check for Signal Strength. \n7. If all else fails, you can perform a factory reset on your router to restore it to its default settings.'],
      ['SI2','Ethernet Cable Connection Error','1.Ensure that the Ethernet cable is securely plugged into both your computers Ethernet port and the network switch or router. \n2. Verify that your computer is set to obtain an IP address automatically (using DHCP). Incorrect IP settings can lead to connectivity problems. \n3. Your firewall or security software may be blocking your Ethernet connection. Temporarily disable these software applications to see if they are the cause of the problem. \n4. Reset TCP/IP stack for Windows. '],
      ['SI3','Unable to connect to the Bluetooth device.','1. Make sure Bluetooth is enabled on your computer. In Windows, you can do this by going to Settings > Devices > Bluetooth & other devices. \n2. Verify that your Bluetooth device is compatible with your computer and its operating system. \n3. Try removing the device from your computers list of paired devices and then re-pair it \n4. Update Bluetooth Drivers.'],
      ['SI4','LAN(Local Area Network) Issues','1. If you have no network connectivity at all, first ensure that the LAN cable (for wired connections) is securely connected and that your network adapter is enabled in your computers settings. \n2. Ensure that your computer is set to obtain an IP address automatically for both wired and wireless LAN connections. \n3. Reboot the modem. \n4. Update the network drivers. \n5. Restart your computer.']
    ]

def get_sol(issue):
    for i in range(len(data)):
        if(data[i][0]==issue):
            return(data[i][1], data[i][2])
    return("No solution found")